name: bidchain

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: bidchain-client
    ports:
      - '5174:3000'
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - './client/.env'

  server:
    build:
      context: ./server
      dockerfile: DockerFile
    image: bidchain-server
    restart: always
    ports:
      - '8080:8080'
      - '8081:8081'
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - PORT=8080

  db:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - './server/.env.docker'
    volumes:
      - pgdata-primary:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: bidchain-db
      POSTGRES_HOST_AUTH_METHOD: md5

volumes:
  pgdata-primary:
